<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Product>Aviscribe</Product>
    <Company>xTektonic</Company>
    <Authors>xTektonic</Authors>
    <Version>1.0.4</Version>
    <AssemblyVersion>1.0.4.0</AssemblyVersion>
    <FileVersion>1.0.4.0</FileVersion>
    <RepositoryUrl>https://github.com/xTektonic/Aviscribe</RepositoryUrl>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
