<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<EnableCsWinRT>true</EnableCsWinRT>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.0" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aviscribe.Core\Aviscribe.Core.csproj" />
    <ProjectReference Include="..\Aviscribe.UI\Aviscribe.UI.csproj" />
    <ProjectReference Include="..\Aviscribe.Windows.Capture\Aviscribe.Windows.Capture.csproj" />
  </ItemGroup>

</Project>
