<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FlashCap" Version="1.11.9" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aviscribe.Core.Capture\Aviscribe.Core.Capture.csproj" />
  </ItemGroup>
</Project>
